### ISSUE TITLE
libimobiledevice latest version

### ISSUE THREAD

**Issue by outsourcestudio** [Ren-Qan/LibIMobileDevice-Debug#1]
Hello!
I try to build Mac OS app with iPhone backup functionality.
in logs I have MOBILEBACKUP2_E_BAD_VERSION when run 
mobilebackup2_client_start_service(this->mDevice, &mb_client, NULL);
I tried to install libimobiledevice via homebrew
idevicebackup2 -d backup
I got Could not perform backup protocol version exchange, error code -1
I'm not alone
https://github.com/libimobiledevice/libimobiledevice/issues/1299
and all advices are about using last source code.
I thought project uses the latest library ? Any advice how to update library and I can create pull request after update.
Thanks!

**Comment by Ren-Qan** [comment]
> Hello! I try to build Mac OS app with iPhone backup functionality. in logs I have MOBILEBACKUP2_E_BAD_VERSION when run mobilebackup2_client_start_service(this->mDevice, &mb_client, NULL); I tried to install libimobiledevice via homebrew idevicebackup2 -d backup I got Could not perform backup protocol version exchange, error code -1 I'm not alone [libimobiledevice/libimobiledevice#1299](https://github.com/libimobiledevice/libimobiledevice/issues/1299) and all advices are about using last source code. I thought project uses the latest library ? Any advice how to update library and I can create pull request after update. Thanks!

![image](https://user-images.githubusercontent.com/17810210/217418190-d52573a3-9997-4203-8510-34111fe56c32.png)

- device:
   model: iphone 13 pro max
   os: 16.1

**Comment by Ren-Qan** [comment]
> Hello! I try to build Mac OS app with iPhone backup functionality. in logs I have MOBILEBACKUP2_E_BAD_VERSION when run mobilebackup2_client_start_service(this->mDevice, &mb_client, NULL); I tried to install libimobiledevice via homebrew idevicebackup2 -d backup I got Could not perform backup protocol version exchange, error code -1 I'm not alone [libimobiledevice/libimobiledevice#1299](https://github.com/libimobiledevice/libimobiledevice/issues/1299) and all advices are about using last source code. I thought project uses the latest library ? Any advice how to update library and I can create pull request after update. Thanks!

![image](https://user-images.githubusercontent.com/17810210/217419371-c31c1581-df68-4ec4-ba90-b2f0e1e298d1.png)

- device:
   model: iphone 13 pro max
   os: 16.1

**Comment by outsourcestudio** [comment]
Thank you so much @Ren-Qan !

**Comment by outsourcestudio** [comment]
Hello @Ren-Qan !
Could you please help us to build Mac OS app to backup decrypted files if you have a free time?
Thanks!
